version: "3.9"

networks:
  internal:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:${SQL_VER}-latest
    container_name: "${APP_NAME}-sql"
    hostname: "${APP_NAME}-sql"
    ports:
      - ${DB_PORT}:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./backup:/var/opt/mssql/backup
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASS}
    networks:
      - internal

volumes:
  db_data:
  db_admin_data:
